spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/telemetry/{application}
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/