spring:
  kafka:
    bootstrapServer: localhost:9092
    snapshot:
      group:
        id: analyzer
      topic:
        in: telemetry.snapshots.v1
    hub:
      group:
        id: analyzer
      topic:
        in: telemetry.hubs.v1
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show_sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/analyzer
    username: analyzer
    password: analyzer
grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext